server:
  port: 8080

saleson:
  application.name: saleson-front-jsp

  url:
    backoffice: https://saleson4.onlinepowers.com
    api: https://saleson4.onlinepowers.com
    frontend: https://saleson4.onlinepowers.com
    cdn:

  version: "4.0.0"
  root: ""
  static-root: ${saleson.root}/storage
  storage-root: ${saleson.root}/static


logging:
  level:
    org.springframework.web: INFO
